
package com.amazonaws.ec2.doc._2008_12_01;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AmazonEC2", targetNamespace = "http://ec2.amazonaws.com/doc/2008-12-01/", wsdlLocation = "http://s3.amazonaws.com/ec2-downloads/ec2.wsdl")
public class AmazonEC2
    extends Service
{

    private final static URL AMAZONEC2_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.amazonaws.ec2.doc._2008_12_01.AmazonEC2 .class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.amazonaws.ec2.doc._2008_12_01.AmazonEC2 .class.getResource(".");
            url = new URL(baseUrl, "http://s3.amazonaws.com/ec2-downloads/ec2.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://s3.amazonaws.com/ec2-downloads/ec2.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        AMAZONEC2_WSDL_LOCATION = url;
    }

    public AmazonEC2(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AmazonEC2() {
        super(AMAZONEC2_WSDL_LOCATION, new QName("http://ec2.amazonaws.com/doc/2008-12-01/", "AmazonEC2"));
    }

    /**
     * 
     * @return
     *     returns AmazonEC2PortType
     */
    @WebEndpoint(name = "AmazonEC2Port")
    public AmazonEC2PortType getAmazonEC2Port() {
        return super.getPort(new QName("http://ec2.amazonaws.com/doc/2008-12-01/", "AmazonEC2Port"), AmazonEC2PortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AmazonEC2PortType
     */
    @WebEndpoint(name = "AmazonEC2Port")
    public AmazonEC2PortType getAmazonEC2Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://ec2.amazonaws.com/doc/2008-12-01/", "AmazonEC2Port"), AmazonEC2PortType.class, features);
    }

}
