
  DROP TABLE SERVANTS ;
  DROP TABLE POOL_DATA;
  DROP TABLE NODE_DATA;

  CREATE TABLE SERVANTS 
   (	
   		NAME VARCHAR(1000) NOT NULL , 
	    IN_USE INTEGER NOT NULL , 
    	PING_FAILURES INTEGER NOT NULL ,
		NODE_NAME VARCHAR(100), 

		REGISTER_TIME TIMESTAMP, 
		PROCESS_ID VARCHAR(100),
		HOST_NAME VARCHAR(500),	
        HOST_IP VARCHAR(100),
        OS VARCHAR(100),

		BORROW_TIME TIMESTAMP, 
		BORROW_PROCESS_ID VARCHAR(100),
		BORROW_HOST_NAME VARCHAR(500),	
        BORROW_HOST_IP VARCHAR(100),

		RETURN_TIME TIMESTAMP, 
		RETURN_PROCESS_ID VARCHAR(100),
		RETURN_HOST_NAME VARCHAR(500),	
        RETURN_HOST_IP VARCHAR(100),

        CODEBASE VARCHAR(500),	
       	STUB_HEX VARCHAR(4000) NOT NULL , 
       	BORROW_SESSION_INFO_HEX VARCHAR(4000),
		ATTRIBUTES_HEX VARCHAR(4000),

		JOB_ID VARCHAR(100),
		JOB_NAME VARCHAR(100),
		NOTIFY_EMAIL VARCHAR(100),
		NOTIFIED INTEGER,
        
	 	CONSTRAINT UNIQUE_NAME UNIQUE (NAME) 
   ) ;
   
   CREATE TABLE POOL_DATA  (
        POOL_NAME VARCHAR(1000) NOT NULL, 
        TIMEOUT INTEGER,
        POOL_PREFIXES VARCHAR(1000) NOT NULL, 
        CONSTRAINT UNIQUE__POOL_NAME UNIQUE (POOL_NAME)
   );
   
   CREATE TABLE NODE_DATA  (
		NODE_NAME VARCHAR(100) NOT NULL,
		NODE_TYPE VARCHAR(50),   		
		HOST_IP VARCHAR(100) NOT NULL, 		
		POOL_PREFIX VARCHAR(1000) NOT NULL,		
		HOST_NAME VARCHAR(100), 
		LOGIN VARCHAR(100), 
		PWD VARCHAR(400),
		INSTALL_DIR VARCHAR(400),
		CREATE_SERVANT_COMMAND VARCHAR(400),
		KILL_SERVANT_COMMAND VARCHAR(400),
		OS VARCHAR(100),
		SERVANT_NBR_MIN INTEGER NOT NULL,
		SERVANT_NBR_MAX INTEGER NOT NULL,				
		PROCESS_COUNTER INTEGER NOT NULL,
		CONSTRAINT UNIQUE_NODE_NAME UNIQUE (NODE_NAME)		
	);
			      
   CREATE INDEX stubs_idx ON SERVANTS (STUB_HEX);   
  
   COMMIT;
 
